services:
  - type: web
    name: freshfromhome-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MERCHANT_UPI_ID
        value: annemnagapranitheswarreddy45-2@okicici
      - key: MERCHANT_PAYEE_NAME
        value: ANNEM NAGA PRANITHESWARREDDY

  - type: web
    name: freshfromhome-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: freshfromhome-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: NODE_ENV
        value: production
